In [25]:
import numpy as np
import pandas as pd

In [26]:
data = pd.read_csv("data_ffnn_3classes.txt",header = None,sep=" ")
V_neuron= 10
W_neuron = 3

In [27]:
# FRONT PROPAGATION
def YMatrix(data):
    Y = [[],[],[]]
    for y in data:
        if y == 0:
            Y[0].append(1)
            Y[1].append(0)
            Y[2].append(0)
        elif y == 1:
            Y[0].append(0)
            Y[1].append(1)
            Y[2].append(0)
        elif y == 2:
            Y[0].append(0)
            Y[1].append(0)
            Y[2].append(1)
    return np.array(Y).transpose()
            

def X2Matrix(X):
    ones = np.ones(((np.size(X,0)),1))
    return np.append(ones,X,axis=1)

def X3Matrix(X,V):
    return X.dot(V)
    
def FMatrix(X):
    return 1/(1 + np.exp(-X))

def F2Matrix(F):
    ones = np.ones((np.size(F,0),1))
    return np.append(ones,F,axis=1)

def F3Matrix(F,W):
    return F.dot(W)

def GMatrix(F):
    return 1/(1 + np.exp(-F))

def Error(G,Y):
    squares = (G - Y ) ** 2
    return np.sum(squares)/2

In [28]:
# BACK PROPAGATION

def W_Correction(G,Y,F,W,a):
    W2 = np.zeros((np.size(W,0),np.size(W,1)))
    for k in range(np.size(W,0)):
        for j in range(np.size(W,1)):
            w = W[k][j]
            err = 0
            for i in range(np.size(G,1)):
                g = G[i][j]
                y = Y[i][j]
                f = F[i][k]
                
                err += (g-y) * g * (1-g) * f
            W2[k][j] = w - (a*err)
    return W2

In [29]:
# FFNN
# 
# def FFNN():
#     

In [30]:
print(data)
Y_Matrix = YMatrix(data[2])
X_Matrix = np.array([data[0],data[1]]).transpose()
X2_Mat = X2Matrix(X_Matrix)


V_Mat = np.random.rand(np.size(X2_Mat,1),V_neuron)

X3_Mat = X3Matrix(X2_Mat,V_Mat)

F_Mat = FMatrix(X3_Mat)
F2_Mat = F2Matrix(F_Mat)

W_Mat = np.random.rand(V_neuron+1,W_neuron)

F3_Mat = F3Matrix(F2_Mat,W_Mat)

G_Mat = GMatrix(F3_Mat)

# TODO NOT suppose to be transpose !!!!!
E_Mat = Error(G_Mat,Y_Matrix)

N_W_Mat = W_Correction(G_Mat,Y_Matrix,F2_Mat,W_Mat,0.5)

print(W_Mat)
print("\n")
print(N_W_Mat)

         0       1    2
0   1.9643  4.5957  1.0
1   2.2753  3.8589  1.0
2   2.9781  4.5651  1.0
3   2.9320  3.5519  1.0
4   3.5772  2.8560  1.0
..     ...     ...  ...
66  4.7483  0.7251  2.0
67  4.2916  1.0857  2.0
68  4.7126  0.8640  2.0
69  4.1005  1.0058  2.0
70  3.9601  1.4057  2.0

[71 rows x 3 columns]
[[0.40618805 0.819211   0.51796053]
 [0.28302427 0.99535218 0.06289103]
 [0.89894614 0.36646002 0.32540356]
 [0.29426918 0.66523692 0.43756582]
 [0.39921444 0.34077812 0.50039232]
 [0.48831538 0.87065915 0.60954093]
 [0.72684606 0.13443212 0.72664529]
 [0.93347577 0.46466529 0.92056566]
 [0.38923997 0.96350586 0.56471664]
 [0.02277963 0.69992566 0.87598663]
 [0.95203979 0.95526491 0.79631889]]


[[0.39911654 0.81921321 0.51394221]
 [0.27719497 0.995354   0.05957799]
 [0.89292518 0.3664619  0.32198179]
 [0.28749969 0.66523904 0.43371881]
 [0.39384448 0.3407798  0.4973406 ]
 [0.48127863 0.87066136 0.60554235]
 [0.71980796 0.13443432 0.72264594]
 [0.92693405 0.46466733 0.91684799]
 [